-- OptionTrap PostgreSQL schema
-- Mirrors the SQLite schema defined in server/db.js exactly.
--
-- Type mapping notes (SQLite -> Postgres):
--   TEXT                         -> TEXT
--   INTEGER                      -> BIGINT
--   REAL                         -> DOUBLE PRECISION
--   INTEGER PRIMARY KEY AUTOINC  -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   datetime('now') default      -> to_char(now(), 'YYYY-MM-DD HH24:MI:SS') to keep the
--                                   same "YYYY-MM-DD HH:MM:SS" TEXT format SQLite emits.
--   exited INTEGER (0/1)         -> kept as INTEGER to mirror SQLite (no app code change).

CREATE TABLE IF NOT EXISTS users (
  user_id    TEXT PRIMARY KEY,
  user_name  TEXT,
  updated_at TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS sessions (
  sid     TEXT PRIMARY KEY,
  data    TEXT NOT NULL,
  expires BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS watchlists (
  id         TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL,
  name       TEXT NOT NULL,
  sort_order BIGINT NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS watchlist_items (
  id               TEXT PRIMARY KEY,
  watchlist_id     TEXT NOT NULL,
  instrument_token BIGINT NOT NULL,
  tradingsymbol    TEXT NOT NULL,
  exchange         TEXT NOT NULL DEFAULT 'NSE',
  sort_order       BIGINT NOT NULL DEFAULT 0,
  added_at         TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY (watchlist_id) REFERENCES watchlists(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS instruments (
  instrument_token BIGINT PRIMARY KEY,
  exchange_token   BIGINT NOT NULL,
  tradingsymbol    TEXT NOT NULL,
  name             TEXT NOT NULL,
  exchange         TEXT NOT NULL DEFAULT 'NSE',
  instrument_type  TEXT NOT NULL DEFAULT 'EQ',
  strike           DOUBLE PRECISION,
  expiry           TEXT,
  lot_size         BIGINT
);

CREATE TABLE IF NOT EXISTS instruments_meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS positions (
  id                TEXT PRIMARY KEY,
  user_id           TEXT NOT NULL,
  mode              TEXT NOT NULL DEFAULT 'paper',
  tradingsymbol     TEXT NOT NULL,
  instrument_token  BIGINT NOT NULL,
  strike            DOUBLE PRECISION NOT NULL,
  option_type       TEXT NOT NULL,
  side              TEXT NOT NULL,
  quantity          BIGINT NOT NULL,
  entry_price       DOUBLE PRECISION NOT NULL,
  entry_time        TEXT NOT NULL,
  expiry            TEXT NOT NULL,
  exited            INTEGER NOT NULL DEFAULT 0,
  exit_price        DOUBLE PRECISION,
  exit_time         TEXT,
  note              TEXT,
  target_price      DOUBLE PRECISION,
  stop_loss_price   DOUBLE PRECISION,
  strategy_tag      TEXT,
  confidence        BIGINT
);

CREATE TABLE IF NOT EXISTS oi_snapshots (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp  BIGINT NOT NULL,
  time_label TEXT NOT NULL,
  data       TEXT NOT NULL,
  prices     TEXT,
  close      TEXT,
  spot       DOUBLE PRECISION,
  volumes    TEXT
);

CREATE INDEX IF NOT EXISTS idx_oi_snapshots_timestamp ON oi_snapshots(timestamp);

CREATE TABLE IF NOT EXISTS oi_history (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scrip            TEXT NOT NULL,
  date             TEXT NOT NULL,
  instrument_token BIGINT NOT NULL,
  tradingsymbol    TEXT NOT NULL,
  strike           DOUBLE PRECISION,
  option_type      TEXT,
  expiry           TEXT,
  open             DOUBLE PRECISION,
  high             DOUBLE PRECISION,
  low              DOUBLE PRECISION,
  close            DOUBLE PRECISION,
  volume           BIGINT,
  oi               BIGINT,
  spot_close       DOUBLE PRECISION,
  UNIQUE(scrip, date, instrument_token)
);

CREATE INDEX IF NOT EXISTS idx_oi_history_scrip_date ON oi_history(scrip, date);

-- Migration tracking table (mirrors the concept used by the SQLite app).
CREATE TABLE IF NOT EXISTS schema_migrations (
  name       TEXT PRIMARY KEY,
  checksum   TEXT NOT NULL,
  applied_at TEXT DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);
